### ISSUE TITLE
vdj combination tab does not appera correctly

### ISSUE THREAD

**Issue by npechl** [NatAnastas/immunovisual#9]
This is the front page of immunovisual:

![image](https://github.com/NatAnastas/immunovisual/assets/44325851/db69d0bf-8e47-4492-84c2-f5fe98ea8827)

when the user chooses sth else (for example color palettes)

![image](https://github.com/NatAnastas/immunovisual/assets/44325851/925fbdc5-e8e9-4dc1-990d-786ac7f67a8d)

**Comment by natanast** [comment]
done

**Comment by npechl** [comment]
Same problem applied in other tabs too

![image](https://github.com/NatAnastas/immunovisual/assets/44325851/7c532bee-a14d-40f8-9d0e-567d6d4eb000)

**Comment by natanast** [comment]
Fixed it. VDJ combination tab is now at Repertoire-level exploration drop down menu.

**Comment by npechl** [comment]
thank you. it is fixed!
